services:
    hikka:
        build: docker
        container_name: hikka
        volumes:
            - ./data:/data
            - ./venv:/venv
        ports:
            - "8080:8080"
        environment:
            - USE_VENV=true